[package]
name = "ia-get"
categories = ["command-line-utilities"]
description = "File downloader for archive.org"
keywords = ["cli", "archive", "internet-archive", "download"]
authors = ["Martin Wimpress <code@wimpress.io>"]
repository = "https://github.com/wimpysworld/ia-get"
readme = "README.md"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.18.0"
md5 = "0.8.0"
reqwest = { version = "0.12.23", default-features = false, features = ["rustls-tls", "stream"] }
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros", "fs", "io-util", "signal"] }
serde = { version = "1.0.219", features = ["derive"] }
serde-xml-rs = "0.8.1"
thiserror = "2.0.16"
url = "2.5.7"
clap = { version = "4.5.45", features = ["derive"] }
ctrlc = "3.4.7"
colored = "3.0.0"
chrono = "0.4.41"
serde_json = "1.0.143"
toml = "0.9.5"
futures-util = "0.3"
anyhow = "1.0"
flate2 = "1.0"
bzip2 = "0.6.0"
xz2 = "0.1"
tar = "0.4"

[dev-dependencies]
tempfile = "3.0"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
