name: internet_archive_helper
description: Internet Archive Helper - Mobile app for downloading files from the Internet Archive
version: 1.6.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # FFI for Rust integration
  ffi: ^2.1.4
  
  # UI and state management
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  
  # Storage and file management
  path_provider: ^2.1.5
  permission_handler: ^12.0.0
  
  # Network and download
  http: ^1.5.0
  dio: ^5.9.0
  
  # UI enhancements
  flutter_spinkit: ^5.2.2
  percent_indicator: ^4.2.5
  
  # Utilities
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/