name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Cancel previous runs when new commits are pushed to the same PR/branch
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  # Optimize Cargo for CI/CD performance
  CARGO_NET_RETRY: 10
  CARGO_NET_TIMEOUT: 60
  CARGO_HTTP_TIMEOUT: 60
  CARGO_HTTP_LOW_SPEED_LIMIT: 10
  # Use offline mode when possible to prefer cached dependencies
  CARGO_NET_OFFLINE: false
  # Enable incremental compilation for faster builds
  CARGO_INCREMENTAL: 1

jobs:
  test:
    name: Test and Build (${{ matrix.os }}, ${{ matrix.features }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        features: [cli, gui]
        include:
          - features: cli
            feature_flags: "--no-default-features --features cli"
            cache_suffix: "cli"
          - features: gui  
            feature_flags: "--features gui"
            cache_suffix: "gui"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache Rust toolchain
      uses: actions/cache@v4
      with:
        path: |
          ~/.rustup/toolchains
          ~/.rustup/update-hashes
          ~/.rustup/settings.toml
        key: ${{ runner.os }}-rustup-stable-${{ hashFiles('rust-toolchain.toml', 'Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-rustup-stable-
          ${{ runner.os }}-rustup-

    - name: Cache Cargo registry and dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          # Windows-specific paths
          ${{ runner.os == 'Windows' && 'C:\Users\runneradmin\.cargo\registry\' || '' }}
          ${{ runner.os == 'Windows' && 'C:\Users\runneradmin\.cargo\git\' || '' }}
        key: ${{ runner.os }}-${{ matrix.cache_suffix }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.cache_suffix }}-cargo-${{ hashFiles('**/Cargo.lock') }}-
          ${{ runner.os }}-${{ matrix.cache_suffix }}-cargo-
          ${{ runner.os }}-cargo-

    - name: Cache build artifacts by target
      uses: actions/cache@v4
      with:
        path: |
          target/debug/deps/
          target/debug/build/
          target/debug/.fingerprint/
          target/release/deps/
          target/release/build/
          target/release/.fingerprint/
        key: ${{ runner.os }}-${{ matrix.cache_suffix }}-target-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('src/**/*.rs') }}-${{ hashFiles('build.rs') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.cache_suffix }}-target-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('src/**/*.rs') }}-
          ${{ runner.os }}-${{ matrix.cache_suffix }}-target-${{ hashFiles('**/Cargo.lock') }}-
          ${{ runner.os }}-${{ matrix.cache_suffix }}-target-
          ${{ runner.os }}-target-

    - name: Warm up dependency cache
      run: |
        # Pre-fetch dependencies to populate cache
        cargo fetch --verbose
        # Verify cache integrity and show cache statistics
        echo "=== Cache Statistics ==="
        echo "Cargo cache size:"
        if command -v du > /dev/null 2>&1; then
          du -sh ~/.cargo/ 2>/dev/null || echo "Cache size check not available"
        else
          echo "Cache size check not available on this platform"
        fi
        echo "Target directory size:"
        if command -v du > /dev/null 2>&1; then
          du -sh target/ 2>/dev/null || echo "Target size check not available"
        else
          echo "Target size check not available on this platform"
        fi
        # Verify dependencies are available offline
        cargo tree --quiet > /dev/null 2>&1 || echo "Cache warming completed"

    - name: Optimize cache for build speed
      run: |
        # Set environment variables for optimized builds
        echo "CARGO_NET_OFFLINE=true" >> $GITHUB_ENV
        echo "CARGO_TARGET_DIR=target" >> $GITHUB_ENV

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Run clippy
      run: cargo clippy ${{ matrix.feature_flags }} --all-targets -- -D warnings

    - name: Build (${{ matrix.features }} features)
      run: cargo build ${{ matrix.feature_flags }} --release

    - name: Run tests (${{ matrix.features }} features)
      run: cargo test ${{ matrix.feature_flags }}

    - name: Run build validation script (Windows only)
      if: runner.os == 'Windows' && matrix.features == 'gui'
      run: .\scripts\validate-build.ps1
      shell: pwsh

    - name: Create artifact (using build script)
      if: matrix.features == 'gui'
      shell: bash
      run: |
        # The build script already creates artifacts in the artifacts/ directory
        # Just verify they exist and calculate hashes
        if [ -d "artifacts" ]; then
          cd artifacts
          echo "# Calculated SHA256 hashes:" > ../hashes_${{ runner.os }}_${{ matrix.features }}.txt
          for file in *; do
            if [ -f "$file" ]; then
              if command -v sha256sum > /dev/null 2>&1; then
                hash=$(sha256sum "$file" | cut -d' ' -f1)
                echo "SHA256 for $file: $hash"
                echo "$hash  $file" >> ../hashes_${{ runner.os }}_${{ matrix.features }}.txt
              elif command -v shasum > /dev/null 2>&1; then
                hash=$(shasum -a 256 "$file" | cut -d' ' -f1)
                echo "SHA256 for $file: $hash"
                echo "$hash  $file" >> ../hashes_${{ runner.os }}_${{ matrix.features }}.txt
              else
                echo "SHA256 calculation not available for $file" >> ../hashes_${{ runner.os }}_${{ matrix.features }}.txt
              fi
            fi
          done
        else
          echo "No artifacts directory found, creating basic artifact..."
          mkdir -p artifacts
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cp target/release/ia-get.exe artifacts/
          else
            cp target/release/ia-get artifacts/
          fi
        fi

    - name: Upload artifact
      if: matrix.features == 'gui'
      uses: actions/upload-artifact@v4
      with:
        name: ia-get-${{ runner.os }}-${{ matrix.features }}
        path: |
          artifacts/*
          hashes_${{ runner.os }}_${{ matrix.features }}.txt
        retention-days: 30

    - name: Cache cleanup and optimization
      if: always()
      shell: pwsh
      run: |
        # Clean up target directory to keep cache size manageable  
        try { cargo clean --target-dir target/debug } catch { Write-Host "Debug clean failed, continuing..." }
        
        # Remove old incremental compilation artifacts
        Get-ChildItem -Path target/ -Recurse -Directory -Name "incremental" -ErrorAction SilentlyContinue | ForEach-Object { 
            try { 
                Remove-Item -Path "target/$_" -Recurse -Force -ErrorAction SilentlyContinue
                Write-Host "Removed incremental cache: target/$_"
            } catch {
                Write-Host "Could not remove target/$_"
            }
        }
        
        Write-Host "Cache cleanup completed"

  release:
    name: Create Development Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: release-artifacts
        pattern: ia-get-*-gui  # Only download GUI artifacts for release

    - name: Prepare release artifacts
      run: |
        mkdir -p final-artifacts
        # Flatten artifact directory structure and gather hash information
        find release-artifacts -type f -name "*.tar.gz" -o -name "*.zip" | while read file; do
          [ -f "$file" ] && cp "$file" final-artifacts/
        done
        # Copy binaries
        find release-artifacts -type f -name "ia-get" -o -name "ia-get.exe" | while read file; do
          [ -f "$file" ] && cp "$file" final-artifacts/
        done
        
        cd final-artifacts
        echo "## 📦 Artifact Checksums (SHA256)" > ../HASHES.md
        echo "" >> ../HASHES.md
        
        # Collect hashes from all hash files
        for hash_file in ../release-artifacts/*/hashes_*_gui.txt; do
          if [ -f "$hash_file" ]; then
            # Read each line from the hash file and match with files in final-artifacts
            while IFS= read -r line; do
              if [[ "$line" =~ ^[a-f0-9]{64}[[:space:]]+(.+)$ ]]; then
                hash=$(echo "$line" | cut -d' ' -f1)
                filename=$(echo "$line" | cut -d' ' -f3-)
                if [ -f "$filename" ]; then
                  echo "- **${filename}**: \`${hash}\`" >> ../HASHES.md
                fi
              fi
            done < "$hash_file"
          fi
        done

    - name: Generate release notes
      run: |
        COMMIT_SHA=$(git rev-parse --short HEAD)
        COMMIT_MSG=$(git log -1 --pretty=format:'%s')
        DATE=$(date '+%Y-%m-%d %H:%M:%S UTC')
        
        cat > RELEASE_NOTES.md << EOF
        # 🚀 Development Build - ${COMMIT_SHA}
        
        **Build Date**: ${DATE}  
        **Commit**: ${COMMIT_SHA}  
        **Message**: ${COMMIT_MSG}
        
        ## 📥 Downloads
        
        Choose your platform:
        - **Linux**: \`ia-get-Linux.tar.gz\`
        - **Windows**: \`ia-get-Windows.zip\` 
        - **macOS**: \`ia-get-macOS.tar.gz\`
        
        $(cat HASHES.md)
        
        ## 📋 Recent Changes
        
        $(head -n 50 CHANGELOG.md | tail -n +3)
        
        ---
        *This is an automated development build. For stable releases, see [tagged releases](https://github.com/Gameaday/ia-get-cli/releases).*
        EOF

    - name: Delete previous development release
      continue-on-error: true
      run: |
        if gh release view development >/dev/null 2>&1; then
          gh release delete development --yes
        fi
        if git tag -l | grep -q "^development$"; then
          git push origin :refs/tags/development
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create development release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: development
        name: "🔧 Latest Development Build"
        body_path: RELEASE_NOTES.md
        files: final-artifacts/*
        prerelease: true
        make_latest: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}