name: CI/CD - Flutter Mobile & Web

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [published]

concurrency:
  group: flutter-${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Analyze & Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.0'
        channel: 'stable'
        cache: true
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          mobile/flutter/.dart_tool
          mobile/flutter/build
        key: flutter-${{ hashFiles('mobile/flutter/pubspec.yaml') }}
    
    - name: Get dependencies
      working-directory: mobile/flutter
      run: flutter pub get
    
    - name: Analyze
      working-directory: mobile/flutter
      run: flutter analyze --no-fatal-infos
    
    - name: Test
      working-directory: mobile/flutter
      run: flutter test

  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    needs: analyze
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.0'
        channel: 'stable'
        cache: true
    
    - name: Get dependencies
      working-directory: mobile/flutter
      run: flutter pub get
    
    - name: Build APK
      working-directory: mobile/flutter
      run: flutter build apk --release
    
    - name: Generate checksum
      working-directory: mobile/flutter/build/app/outputs/flutter-apk
      run: sha256sum app-release.apk > app-release.apk.sha256
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ia-get-android
        path: |
          mobile/flutter/build/app/outputs/flutter-apk/app-release.apk
          mobile/flutter/build/app/outputs/flutter-apk/app-release.apk.sha256
        retention-days: 30

  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    needs: analyze
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.0'
        channel: 'stable'
        cache: true
    
    - name: Get dependencies
      working-directory: mobile/flutter
      run: flutter pub get
    
    - name: Build Web
      working-directory: mobile/flutter
      run: flutter build web --release --base-href /ia-get-cli/
    
    - name: Create web archive
      working-directory: mobile/flutter/build
      run: |
        tar czf web-bundle.tar.gz web/
        sha256sum web-bundle.tar.gz > web-bundle.tar.gz.sha256
    
    - name: Upload Web
      uses: actions/upload-artifact@v4
      with:
        name: ia-get-web
        path: |
          mobile/flutter/build/web-bundle.tar.gz
          mobile/flutter/build/web-bundle.tar.gz.sha256
        retention-days: 30

  deploy-web:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-web
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Download web artifact
      uses: actions/download-artifact@v4
      with:
        name: ia-get-web
    
    - name: Extract web build
      run: tar xzf web-bundle.tar.gz
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web
        cname: ${{ github.repository_owner }}.github.io

  release:
    name: Upload to Release
    runs-on: ubuntu-latest
    needs: [build-android, build-web]
    if: github.event_name == 'release'
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Upload to release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/ia-get-android/*
          artifacts/ia-get-web/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
